development:
  salesforce_username: <%= ENV["SALESFORCE_USERNAME"] %>
  salesforce_password: <%= ENV["SALESFORCE_PASSWORD"] %>
  salesforce_security_token: <%= ENV["SALESFORCE_SECURITY_TOKEN"] %>
  salesforce_client_id: <%= ENV["SALESFORCE_CLIENT_ID"] %>
  salesforce_client_secret: <%= ENV["SALESFORCE_CLIENT_SECRET"] %>

test:
  salesforce_username: <%= ENV["SALESFORCE_USERNAME"] %>
  salesforce_password: <%= ENV["SALESFORCE_PASSWORD"] %>
  salesforce_security_token: <%= ENV["SALESFORCE_SECURITY_TOKEN"] %>
  salesforce_client_id: <%= ENV["SALESFORCE_CLIENT_ID"] %>
  salesforce_client_secret: <%= ENV["SALESFORCE_CLIENT_SECRET"] %>

production:
  salesforce_username: <%= ENV["SALESFORCE_USERNAME"] %>
  salesforce_password: <%= ENV["SALESFORCE_PASSWORD"] %>
  salesforce_security_token: <%= ENV["SALESFORCE_SECURITY_TOKEN"] %>
  salesforce_client_id: <%= ENV["SALESFORCE_CLIENT_ID"] %>
  salesforce_client_secret: <%= ENV["SALESFORCE_CLIENT_SECRET"] %>